# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b4d0b17145bfe21fcb4d2ecd7a3a77fba77f98242acdd56a98320516be4f150a65bbfe682968f529713b2e6d02a7aaceb17c5d82b5f59e0de2d861838c95ff3

test:
  secret_key_base: 3dfd7af739f0161a942d0ecb4985ee8428431ebd94060d969d2e5f37660968292c2d53f2b95e07e14215d9fa822f01c01d2de217dfc11501f4c5959811b72c11

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
